apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: statusquarkusio-ju5a
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-pfvt-tenant/status-quarkus-io/statusquarkusio-ju5a@sha256:03fa779a9fb84a62b01f8c0c215f25a516f23daefbdb8ea012b940282561231b
        name: my-java-quarkus
        resources: {}
status: {}
