apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: statusquarkusio-ju5a
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: statusquarkusio-ju5a
    app.kubernetes.io/part-of: status-quarkus-io
  name: statusquarkusio-ju5a
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: statusquarkusio-ju5a
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: statusquarkusio-ju5a
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-pfvt-tenant/status-quarkus-io/statusquarkusio-ju5a@sha256:03fa779a9fb84a62b01f8c0c215f25a516f23daefbdb8ea012b940282561231b
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 9081
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
